#JAMS property configuration file
model = D:/jamsmodels/JAMS-Application/JAMS-Gehlberg/j2k_gehlbergnsk.xml
libs = D:/jamsprojects/J2K/dist/J2K.jar D:/jamsprojects/J2K/dist/bla.jar
debug = 0
infolog = System.out
errorLog = System.out
