#JAMS property configuration file
model = D:/jamsmodels/JAMS-Application/JAMS-Gehlberg/j2k_gehlbergnsk.xml
libs = D:/jamsprojects/J2K/dist/J2K.jar
debug = 1
verbose = off
infolog = D:/jamsinfo.log
errorlog = D:/jamserror.log
